#!/bin/sh

# theme
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

# timezone
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

# log level
uci set system.@system[0].conloglevel='7'
uci set system.@system[0].cronloglevel='8'
uci commit system

# zram
uci set system.@system[0].zram_size_mb='1536'
uci set system.@system[0].zram_comp_algo='lz4'
uci commit system

# ntp server
uci del system.ntp.enabled
uci del system.ntp.enable_server
uci set system.@system[0].log_proto='udp'
uci del system.ntp.server
uci add_list system.ntp.server='ntp1.aliyun.com'
uci add_list system.ntp.server='time1.cloud.tencent.com'
uci add_list system.ntp.server='cn.ntp.org.cn'
uci add_list system.ntp.server='time.apple.com'
uci commit system

# opkg mirror
sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

# nginx
uci del nginx._lan
uci del nginx._redirect2ssl
uci add nginx server
uci rename nginx.@server[0]='_lan'
uci set nginx._lan.server_name='_lan'
uci add_list nginx._lan.listen='80 default_server'
uci add_list nginx._lan.listen='[::]:80 default_server'
#uci add_list nginx._lan.include='restrict_locally'
uci add_list nginx._lan.include='conf.d/*.locations'
uci set nginx._lan.access_log='off; # logd openwrt'
uci commit nginx
/etc/init.d/nginx enabled
/etc/init.d/nginx restart

# aria2
if [ `grep -c rpc-allow-origin-all "/etc/config/aria2"` -eq '0' ];then
    uci add_list aria2.main.extra_settings='rpc-allow-origin-all=true'
    uci commit aria2
fi
if [ `grep -c http-auth-challenge "/etc/config/aria2"` -eq '0' ];then
    uci add_list aria2.main.extra_settings='http-auth-challenge=true'
    uci commit aria2
fi

# docker mirror
if [ `grep -c 163 "/etc/config/dockerd"` -eq '0' ];then
    uci add_list dockerd.globals.registry_mirrors='https://hub-mirror.c.163.com'
    uci commit dockerd
fi

# upnp
uci set upnpd.config.igdv1='1'
uci set upnpd.config.enabled='1'
uci del upnpd.config.enable_upnp
uci del upnpd.config.enable_natpmp
uci set upnpd.config.external_iface='wan'
uci commit upnpd

# dnsmasq
uci set dhcp.lan.ra='hybrid'
uci set dhcp.lan.ndp='hybrid'
uci set dhcp.lan.dhcpv6='hybrid'
uci set dhcp.lan.ra_management='1'
uci del dhcp.@dnsmasq[0].rebind_protection='1'
uci commit dhcp
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

# packet_steering
uci set network.globals.packet_steering='1'
uci commit network
/etc/init.d/network restart

# disable coremark
sed -i '/coremark/d' /etc/crontabs/root
crontab /etc/crontabs/root

# disable linkease
uci set linkease.@linkease[0].enabled='0'
uci commit linkease
/etc/init.d/linkease restart

# link
ln -sf /bin/busybox /bin/top

# luci cache
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache*

exit 0
