#!/bin/sh

. /lib/functions/uci-defaults.sh

devices_setup()
{
    case "$(board_name)" in
    xiaomi,mi-router-wr30u-layout|\
    xiaomi,mi-router-wr30u-stock|\
    xiaomi,mi-router-wr30u-ubootmod)
        [ -f "/etc/config/wireless" ] && [ $(grep -c "default_radio" /etc/config/wireless) -ge '1' ] && {
            uci -q del wireless.default_radio0
            uci -q del wireless.default_radio1
            uci -q del wireless.radio0.disabled
            uci -q del wireless.radio1.disabled
            uci -q set wireless.wifinet0=wifi-iface
            uci -q set wireless.wifinet0.device='radio0'
            uci -q set wireless.wifinet0.mode='ap'
            uci -q set wireless.wifinet0.ssid='Xiaomi_WR30U'
            uci -q set wireless.wifinet0.encryption='none'
            uci -q set wireless.wifinet0.network='lan'
            uci -q set wireless.radio0.htmode='HE40'
            uci -q set wireless.radio0.channel='10'
            uci -q set wireless.radio0.country='AU'
            uci -q set wireless.radio0.cell_density='3'
            uci -q set wireless.radio1.country='AU'
            uci -q set wireless.radio1.cell_density='3'
            uci -q set wireless.wifinet1=wifi-iface
            uci -q set wireless.wifinet1.device='radio1'
            uci -q set wireless.wifinet1.mode='ap'
            uci -q set wireless.wifinet1.ssid='Xiaomi_WR30U_5G'
            uci -q set wireless.wifinet1.encryption='none'
            uci -q set wireless.wifinet1.network='lan'
            uci commit wireless
            /sbin/wifi >/dev/null 2>&1
        }
        ;;
    xiaomi,redmi-router-ax6000-layout|\
    xiaomi,redmi-router-ax6000-stock|\
    xiaomi,redmi-router-ax6000-ubootmod)
        [ -f "/etc/config/wireless" ] && [ $(grep -c "default_radio" /etc/config/wireless) -ge '1' ] && {
            uci -q del wireless.default_radio0
            uci -q del wireless.default_radio1
            uci -q del wireless.radio0.disabled
            uci -q del wireless.radio1.disabled
            uci -q set wireless.wifinet0=wifi-iface
            uci -q set wireless.wifinet0.device='radio0'
            uci -q set wireless.wifinet0.mode='ap'
            uci -q set wireless.wifinet0.ssid='Redmi_AX6000'
            uci -q set wireless.wifinet0.encryption='none'
            uci -q set wireless.wifinet0.network='lan'
            uci -q set wireless.radio0.htmode='HE40'
            uci -q set wireless.radio0.channel='10'
            uci -q set wireless.radio0.country='AU'
            uci -q set wireless.radio0.cell_density='3'
            uci -q set wireless.radio1.country='AU'
            uci -q set wireless.radio1.cell_density='3'
            uci -q set wireless.wifinet1=wifi-iface
            uci -q set wireless.wifinet1.device='radio1'
            uci -q set wireless.wifinet1.mode='ap'
            uci -q set wireless.wifinet1.ssid='Redmi_AX6000_5G'
            uci -q set wireless.wifinet1.encryption='none'
            uci -q set wireless.wifinet1.network='lan'
            uci commit wireless
            /sbin/wifi >/dev/null 2>&1
        }
        ;;
    netcore,n60-pro)
        [ -f "/etc/config/wireless" ] && [ $(grep -c "default_radio" /etc/config/wireless) -ge '1' ] && {
            uci -q del wireless.default_radio0
            uci -q del wireless.default_radio1
            uci -q del wireless.radio0.disabled
            uci -q del wireless.radio1.disabled
            uci -q set wireless.wifinet0=wifi-iface
            uci -q set wireless.wifinet0.device='radio0'
            uci -q set wireless.wifinet0.mode='ap'
            uci -q set wireless.wifinet0.ssid='Netcore_N60_Pro'
            uci -q set wireless.wifinet0.encryption='none'
            uci -q set wireless.wifinet0.network='lan'
            uci -q set wireless.radio0.htmode='HE40'
            uci -q set wireless.radio0.channel='10'
            uci -q set wireless.radio0.country='AU'
            uci -q set wireless.radio0.cell_density='3'
            uci -q set wireless.radio1.country='AU'
            uci -q set wireless.radio1.cell_density='3'
            uci -q set wireless.wifinet1=wifi-iface
            uci -q set wireless.wifinet1.device='radio1'
            uci -q set wireless.wifinet1.mode='ap'
            uci -q set wireless.wifinet1.ssid='Netcore_N60_Pro_5G'
            uci -q set wireless.wifinet1.encryption='none'
            uci -q set wireless.wifinet1.network='lan'
            uci commit wireless
            /sbin/wifi >/dev/null 2>&1
        }
        ;;
    esac
}

# default password - sha256 encryption
default_password='$5$626kbZ5jg7kKWPIt$xm4Vzq.YXM2mwmYgbU8A.bEvUZpR18Wkn0imJlCzSEC'
sed -i "s|^root:[^:]*:|root:${default_password}:|" /etc/shadow

# theme
if [ -d "/www/luci-static/argon" ] && [ -z "$(uci -q get luci.main.pollinterval)" ]; then
    uci set luci.main.mediaurlbase='/luci-static/argon'
    uci set luci.main.pollinterval='3'
    uci commit luci
fi

# timezone
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

# log level
uci set system.@system[0].conloglevel='1'
uci set system.@system[0].cronloglevel='9'
uci commit system

# zram
mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
zram_size=$(echo | awk "{print int($mem_total*0.25/1024)}")
uci set system.@system[0].zram_size_mb="$zram_size"
uci set system.@system[0].zram_comp_algo='lz4'
uci commit system

# opkg mirror
if [ $(grep -c SNAPSHOT /etc/opkg/distfeeds.conf) -eq '0' ]; then
    sed -i 's,downloads.openwrt.org,mirrors.aliyun.com/openwrt,g' /etc/opkg/distfeeds.conf
else
    sed -i 's,downloads.openwrt.org,mirrors.pku.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf
fi

# extra packages
echo "src/gz openwrt_extras https://opkg.cooluc.com/openwrt-24.10/$(. /etc/openwrt_release ; echo $DISTRIB_ARCH)" >> /etc/opkg/distfeeds.conf

# nginx
uci set nginx.global.uci_enable='true'
uci del nginx._lan
uci del nginx._redirect2ssl
uci add nginx server
uci rename nginx.@server[0]='_lan'
uci set nginx._lan.server_name='_lan'
uci add_list nginx._lan.listen='80 default_server'
uci add_list nginx._lan.listen='[::]:80 default_server'
#uci add_list nginx._lan.include='restrict_locally'
uci add_list nginx._lan.include='conf.d/*.locations'
uci set nginx._lan.access_log='off; # logd openwrt'
uci commit nginx
service nginx restart

# diagnostics
if [ $(uci -q get luci.diag.ping) = "openwrt.org" ]; then
    uci set luci.diag.dns='www.qq.com'
    uci set luci.diag.ping='www.qq.com'
    uci set luci.diag.route='www.qq.com'
    uci commit luci
fi

# packet steering
uci -q get network.globals.packet_steering > /dev/null || {
    uci set network.globals='globals'
    uci set network.globals.packet_steering=2
    uci set network.globals.steering_flows='128'
    uci commit network
}

# init
devices_setup

exit 0
